// LevelData.js
.pragma library

var levels = [];

// Прямо здесь проверяем, что массив не пустой
var collections = [
    {
        id: "original",
        name: "Sokoban Original",
        author: "Yoshio Murase",
        file: "levels_original.js",
        description: "1982's Classics",
        count: 50
    },
    {
        id: "extra",
        name: "Extra Levels",
        author: "Various",
        file: "levels_extra.js",
        description: "Extras",
        count: 20
    },
    {
        id: "still_more",
        name: "Still More",
        author: "Various",
        file: "levels_still_more.js",
        description: "Just various levels",
        count: 10
    },
            {
                id: "classics",
                name: "JasonWalt Bab@'s Childhood / Classic",
                author: "Khmelyauskas Alexander Eduardovich",
                file: "levels_JasonWalt_Bab@'s_set.js",
                description: "My favorite levels Collection from My childhood xD",
                count: 15
            },
            {
                id: "for_kids",
                name: "For the Kids",
                author: "Various",
                file: "levels_for_the_kids.js",
                description: "Kids are liking the Easy levels"
            },
            {
                id: "simple",
                name: "Simple Sokoban",
                author: "Various",
                file: "levels_simple_sokoban.js",
                description: "Somebody hate the Hard levels, and prefers \"Super\" easy levels "
            },
            {
                id: "mctommy_inventions",
                name: "McTommy / MacTommy Inventions",
                author: "McTommy",
                file: "levels_mactommy_inventions.js",
                description: "Sokoban Inventions by McTommy"
            },
            {
                id: "yoshios_autogenerated",
                name: "Yoshio's Autogenerated",
                author: "Yoshio Murase",
                file: "levels_yoshios_autogenerated.js",
                description: "Autogenerated levels by Yoshio Murase"
            }

];

function loadPack(fileName) {
    try {
        var path = "qrc:/Level Packs/" + fileName;
        levels = [];
        Qt.include(path);
        console.log("SUCCESS: Pack " + fileName + " loaded. Count: " + levels.length);
        return levels.length > 0;
    } catch (e) {
        console.log("FATAL: Error loading pack: " + e);
        return false;
    }
}
