// LevelData.js
.pragma library

var levels = [];
var currentLoadedFile = "";
var id;
var name;
var author;
var file;
var description;
var count;
var icon

// Прямо здесь проверяем, что массив не пустой
var collections = [
    {
        id: "original",
        name: "Sokoban Original",
        author: "Yoshio Murase",
        file: "levels_original.js",
        description: "1982's Classics",
        count: 50,
                icon: "Assets/Icon_of_Packs/Original_Sokoban.jpg"
    },
    {
        id: "extra",
        name: "Extra Levels",
        author: "Various",
        file: "levels_extra.js",
        description: "Extras",
        count: 20
    },
    {
        id: "still_more",
        name: "Still More",
        author: "Various",
        file: "levels_still_more.js",
        description: "Just various levels",
        count: 10
    },
            {
                id: "classics",
                name: "JasonWalt Bab@'s Childhood / Classic",
                author: "Khmelyauskas Alexander Eduardovich",
                file: "levels_JasonWalt_Bab@s_set.js",
                description: "My favorite levels Collection from My childhood xD",
                icon: "Assets/Icon_of_Packs/JWB_Pack-set_Icon.jpg",
                count: 15
            },
            {
                id: "for_kids",
                name: "For the Kids",
                author: "Various",
                file: "levels_for_the_kids.js",
                description: "Kids are liking the Easy levels",
                count: 10
            },
            {
                id: "simple",
                name: "Simple Sokoban",
                author: "Various",
                file: "levels_simple_sokoban.js",
                description: "Somebody hate the Hard levels, and prefers \"Super\" easy levels",
                count: 50
            },
            {
                id: "mctommy_inventions",
                name: "McTommy / MacTommy Inventions",
                author: "McTommy",
                file: "levels_mactommy_inventions.js",
                description: "Sokoban Inventions by McTommy",
                count: 50
            },
            {
                id: "yoshios_autogenerated",
                name: "Yoshio's Autogenerated",
                author: "Yoshio Murase",
                file: "levels_yoshios_autogenerated.js",
                description: "Autogenerated levels by Yoshio Murase",
                count: 52
            }

];

function loadPack(fileName) {
    // Если этот файл уже загружен, не мучаем систему
    if (currentLoadedFile === fileName && levels.length > 0) {
        console.log("LOG: Pack " + fileName + " is already in memory.");
        return true;
    }

    try {
        var path = "qrc:/Level Packs/" + fileName;
        levels = [];
        Qt.include(path);
        currentLoadedFile = fileName; // Запоминаем, что загрузили
        console.log("SUCCESS: Pack " + fileName + " loaded. Count: " + levels.length);
        return levels.length > 0;
    } catch (e) {
        console.log("ERROR loading pack: " + e);
        return false;
    }
}
